### PR TITLE
Add WWW-Authenticate header to 401 responses

### PR DESCRIPTION
**Pull request by duddo**
Fixing issue [https://github.com/unosquare/embedio/issues/516](516) by adding the WWW-Authenticate header to responses.

### CODE REVIEW

**Comment by duddo** [comment]
#515

**Comment by rdeago** [comment]
Hello @duddo, thanks for the PR! You could commit on your previous PR's branch and GitHub would have updated everything accordingly, no need for a separate branch. Anyway, OK, I'll keep this one and close #515.

**Review by rdeago — APPROVED** [review]
Looks good to me. Great job @duddo!

**Comment by duddo** [comment]
Hello @rdeago, happy to help! 
I issued two separate PR targeting the 3.x and the master branch, since I saw the problem was in both. I caught it first into the nuget package, then I discovered it was present in master too.

**Comment by rdeago** [comment]
@duddo you're right, I just reopened @515 so you can commit the corrected tests on that one too. I apologize for overlooking the target branch.

**Review by geoperez — APPROVED** [review]

**Pull request merged**
