### PR TITLE
Improve performance of web api

### PR DESCRIPTION
**Pull request by Alkalinee**
That should improve the performance of network calls, I just noticed how much reflection was used on each call, that can be drastically improved by caching everything.

Other changes:
- throw a more detailed exception when a path was not found (needed two hours to figure out what the problem is)
- use a TypeConverter instead of finding a parse method.

I just made a small benchmark about that, I just tested calling the ResponseHandler in a loop and the changes of this pull request improve the performance/speed by 16 %.

### CODE REVIEW

**Comment by mariodivece** [comment]
Wow... good work! It's not building though...
`C:\projects\embedio\src\Unosquare.Labs.EmbedIO\Modules\WebApiModule.cs(80,61): error CS1003: Syntax error, ',' expected
C:\projects\embedio\src\Unosquare.Labs.EmbedIO\Modules\WebApiModule.cs(80,108): error CS1003: Syntax error, ',' expected`

**Comment by Alkalinee** [comment]
I don't really understand why these tests fail, I double-checked [the file which is producing the error](https://github.com/CodeElements/embedio/blob/master/src/Unosquare.Labs.EmbedIO/Modules/WebApiModule.cs#L80) and the two ',' are exactly where they should be - if I copy the code directly into VS I don't get any errors.

Travis shows that the two tests with DOTNETCORE=1 are failing (while the tests with `no environment variables set` succeed), my VS doesn't allow me to open the xproj-file, but I don't know how two missing comas can be related to .Net Core.

**Comment by geoperez** [comment]
I think the issue is because it's using out var, use out only and declare the vars before.

**Comment by geoperez** [comment]
Accepting PR into a new branch to resolve issues. Thank you.

**Comment by Alkalinee** [comment]
I'm sorry, just installed the .Net Core packages but I still can't manage to make VS open the project, for some reason it fails to restore the packages because I'm getting 500 errors, even the `System`-namespace import is an error. When creating this pull request, I wasn't really sure if you actually cared about these changes, I have no experience with .Net Core and I'm using this library with .Net/Mono (I knew that I would have to check if .Net Core likes these changes but first I wanted to know if you consider these changes useful).

Anyways, thank you for this project, I really like that I have to write like 20 lines of code and I have a functional web server which responses to different urls, well done :)

**Comment by geoperez** [comment]
Don't worry, i'll let you know when release is done.

**Pull request merged**
