### PR TITLE
new auth module

### PR DESCRIPTION
**Pull request by Tymonrare**
I've added basic authentication module. In simple scenario it will be show auth pop-up in browser.
You can add multiple accounts for sharing permissions.
Also you can check what account sent request with `GetAccountData`

### CODE REVIEW

**Comment by Tymonrare** [comment]
> Build worker image not found: Ubuntu
Is that my fail or not?

**Comment by geoperez** [comment]
Hi @Tymonrare , thank you for the module. One thing, can you change the documentation to [XML Documentation](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/xml-documentation-comments).

**Comment by geoperez** [comment]
What do you think @mariodivece ? Should we keep it here or maybe in Extras?

**Comment by Tymonrare** [comment]
@geoperez fixed.

I suppose it will be useful module (Not only for me https://github.com/unosquare/embedio/issues/125). Probably we should expand functionality, but right now i need only login pop-up with in my app

**Comment by geoperez** [comment]
Why do you need  System.Security.Principal?

**Comment by Tymonrare** [comment]
@geoperez woops) Don't need it. Also i see strange things happening with whitespaces in github preview, -don't know why

**Comment by geoperez** [comment]
@Tymonrare , they are some issues yet: https://ci.appveyor.com/project/geoperez/embedio/build/1.13.848/job/t9jtsk4xvjahrbff#L768

**Comment by Tymonrare** [comment]
@geoperez what may cause "The type or namespace name 'Http' does not exist in the namespace 'System.Net'"? 
It exists [according to microsoft](https://msdn.microsoft.com/ru-ru/library/system.net.http(v=vs.118).aspx) and even [used](https://github.com/unosquare/embedio/blob/7b7cc8663f8b6d419477ef9a2ed2b00dfee9e404/test/Unosquare.Labs.EmbedIO.Tests/CorsModuleTest.cs) in this repo

**Comment by geoperez** [comment]
Hi @Tymonrare , sorry for the delay.

The issue is because you need to include the logic from `AuthenticationHeaderValue.Parse`. because some targets do not have the dependency to ` System.Net.Http.dll`.

**Comment by geoperez** [comment]
MONO has an implementation in the following link. But I encourage you not to include the entire logic, and use something simple:

https://github.com/mono/mono/blob/0bcbe39b148bb498742fc68416f8293ccd350fb6/mcs/class/System.Net.Http/System.Net.Http.Headers/AuthenticationHeaderValue.cs

**Comment by Tymonrare** [comment]
@geoperez removed header parser, recommented code

**Comment by Tymonrare** [comment]
@geoperez wops, sorry for long answer. Yes, i'll do

**Comment by geoperez** [comment]
I'll help you wit the testing in another branch. Thank you.

**Pull request merged**
