### PR TITLE
 Refactor virtual path management of StaticFilesModule (fixes #272 et al.)

### LINKED ISSUE #272: StaticFilesModule: the second and subsequent requests for the same file result in error 404
**Describe the bug**
When `StaticFilesModule` is configured with virtual paths, the first request for a file in a virtual path succeeds, but all subsequent requests result in "404 - Not Found".

**To Reproduce**
1. Have a directory structure as follows:

* /my/path/ _<-- feel free to use a Windows path, the problem is not bound to Unix-like systems_
  * root/
    * file1
  * download/
    * file.zip
  * pictures/
    * photos/
      * photo1.jpg

2. Create a new console application as follows:
```C#
using System;
using System.Threading;
using System.Threading.Tasks;
using Unosquare.Labs.EmbedIO;

namespace MyTest
{
    static class Program
    {
        static void Main()
        {
            using (var cts = new CancellationTokenSource())
            using (var server = new WebServer("http://localhost:8080"))
            {
                server.RegisterModule(new StaticFilesModule(new Dictionary<string, string>() {
                    { "/", "/my/path/root" },
                    { "/download", "/my/path/download" },
                    { "/pictures", "/my/path/pictures" }
                }));
                Task.Run(() => server.RunAsync(cts.Token));
                Console.ReadKey();
            	cts.Cancel();
            }
        }
    }
}
```

3. Start your application.

4. On the same machine, start Chrome (or the browser of your choice), type the following on the address bar, press Enter, and verify that the JPEG file is actually downloaded and displayed:
> `http://localhost:8080/pictures/photos/photo1.jpg`

5. Now request the same file by pressing Ctrl+F5 (or equivalent keystroke / command in non-Chrome browsers, i.e. refresh the page ignoring / discarding cached results)

6. Observe that, instead of downloading the file again, your browser shows you a "404 - Not Found" message.

7. All subsequent requests for the same file fail the same way, until you restart your server application; then you may download the file again - _once_.

**Expected behavior**
I'd expect EmbedIO to serve the same file (as long as it still exists) regardless of how many times a client requests it.

**Server environment**
 - Ubuntu 18.10 / 64 bit
 - Mono 5.20.1
 - EmbedIO v5.4.0 and v5.5.0 

Notice, though, that the described behavior is not apt to change in a different server environment (see the "Additional context" section below).

**Client environment**
 - Windows 10 Pro / 64 bit
 - Chrome 73.0.3683.103 (Official build) (64 bit)

Notice, though, that the described behavior is not apt to change in a different client environment (see the "Additional context" section below).

**Additional context**

The bug disappears if I remove all references to the `_mappedPaths` field in the `VirtualPaths` class. It looks as, once the mapped path for `/pictures/photos/photo1.jpg` is cached, upon subsequent requests EmbedIO looks for the same relative path under a different directory (maybe `/my/path/root/`) instead of `/my/path/pictures/`.

The cause might be that `_mappedPaths` stores relative paths without a reference to the virtual path each of them refers to; then the cache mapped path is used to look for the file under `FileSystemPath`. If in the above example there was a file named `/my/path/root/photos/photo1.jpg`, this is what would be probably served instead of error 404.

**Possible solutions**

There are a few ways to fix this bug:

1. Simply remove `_mappedPaths`. Simplest fix, compatibile with existing code, with a variable impact on performance depending upon the number of files served and the speed of the underlying file system.

2. Control the use of `_mappedPaths` with a `CacheMappedPaths` boolean property (in both `VirtualPaths` and `StaticFilesModule`), defaulting to `true`. Still very easy to do, maximum compatibility, negligible impact on performance (a couple `if`s) if you don't disable caching, otherwise see previous point.

3. Modify `VirtualPaths` so that a reference to the virtual path used is stored with each mapped path. This would also imply other modifications, e.g. removing related entries from `_mappedPaths` in `UnregisterVirtualPath`. Just a bit more complicated, maximum compatibility (unless someone actually _relies_ on this bug for some obscure reason), some impact on both performance and memory footprint, but at least this would be an actual fix, while the previous two were just workarounds.

4. Instead of `VirtualPaths`, make a `VirtualPath` class managing a single virtual path and a `VirtualPathCollection` used by `StaticFilesModule` to manage any number of virtual paths. More work, resulting in simpler and easier to maintain code, with roughly the same pros and cons as the previous one.

There are a couple of more radical possible solutions, but they would introduce breaking changes, so I will stop here for now.

Would it be OK if I submitted a PR with fix number 4?

### PR DESCRIPTION
**Pull request by rdeago**
#### Determinism ####
* Always evaluate virtual path in reverse ordinal order.
* Normalize URL paths to simplify code and ensure consistent mapping.

#### Separation of concerns ####
* Have methods that deal with mapping URL paths to local paths, and other methods that deal with the existence of local paths.

#### Caching ####
* Keep track of _how_ and _why_ paths were mapped.
* Discard cached mapped paths whose generating data (virtual path, default extension, default document name) has changed.

#### Support for changing file systems ####
* Allow the user to deactivate path caching in situations where the contents of served directories may change over time.

#### Compatibility ####
* Keep existing constructors, methods, and properties of `StaticFilesModule`.
* Keep existing exception semantics (e.g. throw `InvalidOperationException` instead of `ArgumentException` for invalid paths passed to `RegisterVirtualPath`).
* Pass all existing unit tests.

### Behavior changes ###
* Scenarios where files could be added to a served directory after being requested (resulting in error 404) are no longer supported: said files will continue to give error 404, unless path caching is disabled.
* Scenarios where files are continuously added and/or deleted, which previously resulted in spurious error 404s (#272), can now be supported by disabling path caching.

### Where do we go from here? ###
There are some modifications I refrained from doing to avoid introducing breaking changes:
* If the `VirtualPaths` property of `StaticFilesModule` returned `IReadOnlyDictionary<string,string>` instead of `ReadOnlyDictionary<string,string>`, its implementation would be leaner and faster.
* It would be rather trivial to remove the need for `StaticFilesModule` to serve the `/` directory (not everybody needs static files there), but then we'd need some different way to initialize it (maybe `StaticFilesSettings` and `StaticFilesSettingsBuilder` objects?)

### CODE REVIEW

**Comment by geoperez** [comment]
Thanks for the PR. 

Regarding your last two items. The type change is fine and the option to remove the root path, it's interesting your idea to include a settings object. We have something similar to initialize the web server.

**Comment by rdeago** [comment]
Thanks a lot @geoperez for merging. #272 was a real show stopper for me.

Regarding future enhancements: new PR coming up shortly, as long as you confirm that breaking changes are not a concern. I'll try to follow the same philosophy as for web server initialization.

One more thing I totally forgot to mention: the path cache could be enabled on a per-virtual-path basis, to support having some folders with _really_ static files, as well as some others with e.g. on-demand reports and such. How about that?

**Comment by geoperez** [comment]
That is really nice, we may need to explain this in the README file. 👍

**Comment by rdeago** [comment]
Fine, I can do that in next PR too.

One more thing that needs a small documentation update: now the final slash on virtual paths is added automatically.

**Pull request merged**
