### PR TITLE
Add or Update a key in the SessionInfo

### PR DESCRIPTION
**Pull request by bufferUnderrun**
Currently, SessionInfo.Data[] only supports adding a key. With this patch, updating is now possible.

Arf, error in the patch. I've forgotten the third parameter of TryUpdate(). Excuse me.

### CODE REVIEW

**Comment by bufferUnderrun** [comment]
The patch i sent is a total craps, i'm tired this morning... I will install vs2015 and correctly test before sending you PR.

**Comment by bufferUnderrun** [comment]
My last patch seems buggy. The 3rd parameter of TryUpdate() must be the old value to change (according to https://msdn.microsoft.com/fr-fr/library/dd287117(v=vs.110).aspx). 

So with `Data.TryUpdate(key, value, value);` Data[key] will not really be updated. 

So, we have to get the old value and pass it as 3rd parameter. But it seems weird.

```C#
        public object this[string key]
        {
            get { return (Data.ContainsKey(key)) ? Data[key] : null; }
            set { 
                if (Data.ContainsKey(key)) {
                    object old_value;
                    old_value = Data.TryGetValue(key, out old_value)
                    Data.TryUpdate(key, value, old_value);
                }
                else {
                    Data.TryAdd(key, value);
                }
            }
        }
```

I'm at work and can't test it for instance. What do you think ?

**Comment by mariodivece** [comment]
It's too much. Simplicity is key here. See my latest commit.
```csharp
        public object this[string key]
        {
            get { return (Data.ContainsKey(key)) ? Data[key] : null; }
            set { Data[key] = value; }
        }
```

**Comment by bufferUnderrun** [comment]
@mariodivece agree much simpler. But i don't see your latest commit with this code ?

**Comment by mariodivece** [comment]
sorry. Forgot to sync. it should be there now.

**Pull request merged**
