### PR TITLE
Fix support for reading multipart post requests.

### PR DESCRIPTION
**Pull request by MarcusWichelmann**
This branch fixes the support of multipart http requests like e.g. file uploads and is the result of serveral hours of debugging. :D

The http request handling code contained a mechanism to detect incompletely received http headers and initiated a second `Stream.ReadAsync` at the end of HttpConnection.cs: OnReadInternal() but it seems like somebody forgot to continue the http-header-parsing after that. (So the code reads the second part of the http header and then instantly discards it without trying to continue the header parsing.)
This caused the file upload using a webbrowser to randomly fail when the browser doesn't send the http header in one single tcp-package because the measurement of the content length might take some time for big files.

This pull requests completes that part of the code to make file uploads work much more reliable.

### CODE REVIEW

**Comment by geoperez** [comment]
Excellent, thank you

**Comment by MarcusWichelmann** [comment]
Wow, that was fast, thank you, too. 👍 
When are you planning to release the next NuGet update so I don't have to use the manually built version of the library much longer?

**Comment by geoperez** [comment]
Probably tomorrow,  I let you know.

**Comment by geoperez** [comment]
I just published the new nuget v1.6.8 (https://www.nuget.org/packages/Embedio)

**Comment by MarcusWichelmann** [comment]
Thank you 👍

**Pull request merged**
